provider "aws" {
  region  = "${var.region}"
  profile = "${var.aws_profile}"
  version = "~> 2.6.0"
}

module "eks" {
  source                          = "../../"
  region                          = "${var.region}"
  vpc_id                          = "${var.vpc_id}"
  private_subnets                 = "${var.private_subnets}"
  public_subnets                  = "${var.public_subnets}"
  cluster_prefix                  = "${var.cluster_prefix}"
  http_proxy                      = "${var.http_proxy}"
  no_proxy                        = "${var.no_proxy}"
  key_name_ops                    = "${var.key_name_ops}"
  key_name_app                    = "${var.key_name_ops}"
  worker_node_sysops_min          = "${var.worker_node_sysops_min}"
  worker_node_sysops_max          = "${var.worker_node_sysops_max}"
  worker_node_sysops_desired      = "${var.worker_node_sysops_desired}"
  worker_node_sysops_instance     = "${var.worker_node_sysops_instance}"
  worker_node_app_min             = "${var.worker_node_app_min}"
  worker_node_app_max             = "${var.worker_node_app_max}"
  worker_node_app_desired         = "${var.worker_node_app_desired}"
  worker_node_app_instance        = "${var.worker_node_app_instance}"
  worker_group_count              = "${var.worker_group_count}"
  aws_authenticator_env_variables = "${local.aws_authenticator_env_variables}"
  tags                            = "${local.tags}"
  cluster_version                 = "${var.cluster_version}"
  enable_cluster_autoscaling      = "${var.enable_cluster_autoscaling}"
  enable_pod_autoscaling          = "${var.enable_pod_autoscaling}"
  install_helm                    = "${var.install_helm}"
  allowed_worker_ssh_cidrs        = "${var.allowed_worker_ssh_cidrs}"
}
